# Generated by Django 5.2.15 on 2026-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file_source',
            field=models.CharField(choices=[('local', 'Local File'), ('external', 'External Link')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/'),
        ),
    ]
