# Generated by Django 5.2.15 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_paid_remove_order_product_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
